apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: hello
  namespace: monitor-apps
spec:
  replicas: 2
  selector:
    deployment-config.name: hello
  strategy:
    resources: {}
    rollingParams:
      intervalSeconds: 1
      maxSurge: 25%
      maxUnavailable: 25%
      timeoutSeconds: 600
      updatePeriodSeconds: 1
    type: Rolling
  template:
    metadata:
      labels:
        deployment-config.name: hello
    spec:
      containers:
      - image: quay.io/redhattraining/probes-hello:v1.0
        imagePullPolicy: Always
        name: default-container
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
  test: false
  triggers:
  - type: ConfigChange
