apiVersion: config.openshift.io/v1
kind: OAuth
metadata:
  name: cluster
spec:
  identityProviders:
  - htpasswd:
      fileData:
        name: compreview-users-secret
    mappingMethod: claim
    name: cluster-users
    type: HTPasswd

