apiVersion: v1
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    labels:
      app: psql
    name: psql
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: psql
        deployment: psql
    strategy:
      resources: {}
    template:
      metadata:
        labels:
          app: psql
          deployment: psql
      spec:
        containers:
        - capabilities: {}
          env:
          - name: POSTGRESQL_DATABASE
            value: db
          - name: POSTGRESQL_PASSWORD
            value: pass
          - name: POSTGRESQL_USER
            value: user
          image: 'registry.access.redhat.com/rhscl/postgresq-96-rhel7:1'
          imagePullPolicy: IfNotPresent
          livenessProbe:
            exec:
              command:
              - /usr/libexec/check-container
              - --live
            initialDelaySeconds: 120
            timeoutSeconds: 10
          name: postgresql
          ports:
          - containerPort: 5432
            protocol: TCP
          readinessProbe:
            exec:
              command:
              - /usr/libexec/check-container
            initialDelaySeconds: 5
            timeoutSeconds: 1
          resources:
            limits:
              memory: 512Mi
          securityContext:
            capabilities: {}
            privileged: false
          terminationMessagePath: /dev/termination-log
          volumeMounts:
          - mountPath: /var/lib/pgsql/data
            name: psql-data
        dnsPolicy: ClusterFirst
        restartPolicy: Always
        volumes:
        - emptyDir:
          name: psql-data
- apiVersion: v1
  kind: Service
  metadata:
    labels:
      app: psql
    name: psql
  spec:
    ports:
    - name: postgres
      nodePort: 0
      port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      name: psql
    sessionAffinity: None
    type: ClusterIP
kind: List
metadata: {}
